export const GET_OFFICES_SUCCESS = "GET_OFFICES_SUCCESS";
export const CREATE_OFFICE_SUCCESS = "CREATE_OFFICE_SUCCESS";
export const CREATE_OFFICE_ERROR = "CREATE_OFFICE_ERROR";
export const DELETE_OFFICE_SUCCESS = "DELETE_OFFICE_SUCCESS";
export const DELETE_OFFICE_ERROR = "DELETE_OFFICE_ERROR";