export const GET_OFFICE_OBJECTS = "GET_OFFICE_OBJECTS";
export const GET_OFFICE_OBJECT_QUEUES = "GET_OFFICE_OBJECT_QUEUES";
export const EDIT_OFFICE_OBJECT_SUCCESS = "EDIT_OFFICE_OBJECT_SUCCESS";
export const EDIT_OFFICE_OBJECT_ERROR = "EDIT_OFFICE_OBJECT_ERROR";
export const CREATE_OFFICE_OBJECT_SUCCESS = "CREATE_OFFICE_OBJECT_SUCCESS";
export const CREATE_OFFICE_OBJECT_ERROR = "CREATE_OFFICE_OBJECT_ERROR";
export const DELETE_OFFICE_OBJECT_SUCCESS = "DELETE_OFFICE_OBJECT_SUCCESS";
export const DELETE_OFFICE_OBJECT_ERROR = "DELETE_OFFICE_OBJECT_ERROR";